services:
  - type: web
    name: cricket-tournament-api
    env: node
    buildCommand: cd Backend && npm install
    startCommand: cd Backend && node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGO_URI
        value: ${MONGO_URI}
      - key: JWT_SECRET
        value: ${JWT_SECRET}
      - key: JWT_EXPIRE
        value: 30d
      - key: FRONTEND_URL
        value: ${FRONTEND_URL}
    plan: free
    autoDeploy: true
